version: '2'
services:
    gt-mgr-app:
        image: gt-mgr
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://gt-mgr-mysql:3306/gt-mgr?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    gt-mgr-mysql:
        extends:
            file: mysql.yml
            service: gt-mgr-mysql
